import type { ToolDefinition } from '../types/tool';

export const tools: ToolDefinition[] = [
  // 1. The Developer Utility Suite
  {
    id: 'json-to-csv',
    slug: 'jsontocsv',
    name: 'JSON to CSV Converter',
    shortName: 'JSON → CSV',
    description: 'Convert JSON data to CSV format instantly with automatic schema detection.',
    longDescription: 'A robust client-side JSON to CSV converter that handles nested objects and arrays.',
    category: 'converters',
    icon: 'file-json',
    keywords: ['json', 'csv', 'converter', 'export'],
    status: 'stable',
    featured: true,
    publishedAt: '2026-06-15',
  },
  {
    id: 'json-formatter',
    slug: 'jsonformatter',
    name: 'JSON Formatter & Validator',
    shortName: 'JSON Format',
    description: 'Prettify and validate messy JSON API responses.',
    longDescription: 'Format, validate, and parse JSON data with clear error reporting and syntax highlighting.',
    category: 'formatters',
    icon: 'code',
    keywords: ['json', 'format', 'validate', 'pretty print'],
    status: 'stable',
    featured: true,
    publishedAt: '2026-06-15',
  },
  {
    id: 'base64-encoder',
    slug: 'base64',
    name: 'Base64 Encoder/Decoder',
    shortName: 'Base64',
    description: 'Encode and decode Base64 strings and files.',
    longDescription: 'Quickly encode to Base64 or decode Base64 strings. Useful for API headers and images.',
    category: 'encoders',
    icon: 'hash',
    keywords: ['base64', 'encode', 'decode'],
    status: 'stable',
    featured: true,
    publishedAt: '2026-06-15',
  },
  {
    id: 'timestamp-converter',
    slug: 'timestamp',
    name: 'Timestamp/Epoch Converter',
    shortName: 'Timestamp',
    description: 'Convert Unix timestamps to human-readable dates.',
    longDescription: 'Essential tool for logs and databases. Converts Unix epoch times to local/UTC dates and vice versa.',
    category: 'dev-tools',
    icon: 'clock',
    keywords: ['epoch', 'timestamp', 'date', 'unix', 'time'],
    status: 'stable',
    featured: false,
    publishedAt: '2026-06-15',
  },
  {
    id: 'regex-tester',
    slug: 'regex',
    name: 'Regex Tester',
    shortName: 'Regex Test',
    description: 'Test your strings against regular expression patterns.',
    longDescription: 'Interactive regex tester with live highlighting and match group extraction.',
    category: 'dev-tools',
    icon: 'search',
    keywords: ['regex', 'regular expression', 'test', 'match'],
    status: 'stable',
    featured: true,
    publishedAt: '2026-06-15',
  },

  // 2. The Content & Data Cleaners
  {
    id: 'html-to-markdown',
    slug: 'htmltomarkdown',
    name: 'HTML to Markdown Converter',
    shortName: 'HTML → MD',
    description: 'Convert HTML code into clean markdown.',
    longDescription: 'Easily turn blog post code into markdown for newsletters or Notion without losing formatting.',
    category: 'converters',
    icon: 'file-text',
    keywords: ['html', 'markdown', 'md', 'convert'],
    status: 'stable',
    featured: false,
    publishedAt: '2026-06-15',
  },
  {
    id: 'word-counter',
    slug: 'wordcounter',
    name: 'Word & Character Counter',
    shortName: 'Word Count',
    description: 'Count words, characters, reading time, and readability score.',
    longDescription: 'Advanced text analysis showing reading time, Flesch-Kincaid readability, and keyword density.',
    category: 'text-tools',
    icon: 'type',
    keywords: ['word count', 'character count', 'reading time', 'readability'],
    status: 'stable',
    featured: false,
    publishedAt: '2026-06-15',
  },
  {
    id: 'url-encoder',
    slug: 'urlencode',
    name: 'URL Encoder/Decoder',
    shortName: 'URL Encode',
    description: 'Encode or decode URL strings safely.',
    longDescription: 'Fix broken tracking links by properly encoding or decoding URL parameters.',
    category: 'encoders',
    icon: 'link',
    keywords: ['url', 'encode', 'decode', 'uri', 'escape'],
    status: 'stable',
    featured: false,
    publishedAt: '2026-06-15',
  },

  // 3. The "Small Task" Generators
  {
    id: 'password-generator',
    slug: 'passwordgen',
    name: 'Secure Password Generator',
    shortName: 'Password Gen',
    description: 'Generate strong, secure passwords locally.',
    longDescription: 'Create highly secure passwords with toggles for symbols, numbers, and length. 100% client-side.',
    category: 'generators',
    icon: 'shield',
    keywords: ['password', 'generate', 'secure', 'random'],
    status: 'stable',
    featured: true,
    publishedAt: '2026-06-15',
  },
  {
    id: 'uuid-generator',
    slug: 'uuid',
    name: 'UUID/GUID Generator',
    shortName: 'UUID Gen',
    description: 'Generate lists of v4 UUIDs instantly.',
    longDescription: 'Generate batches of 10-50 UUIDs with a single click. Ideal for database seeding.',
    category: 'generators',
    icon: 'database',
    keywords: ['uuid', 'guid', 'generate', 'v4', 'random'],
    status: 'stable',
    featured: false,
    publishedAt: '2026-06-15',
  },
  {
    id: 'color-converter',
    slug: 'colorconverter',
    name: 'HEX to RGB/HSL Converter',
    shortName: 'Color Convert',
    description: 'Quickly convert between HEX, RGB, and HSL formats.',
    longDescription: 'A rapid color conversion tool for designers and developers.',
    category: 'dev-tools',
    icon: 'aperture',
    keywords: ['color', 'hex', 'rgb', 'hsl', 'convert'],
    status: 'stable',
    featured: false,
    publishedAt: '2026-06-15',
  },
  {
    id: 'text-diff',
    slug: 'textdiff',
    name: 'Text Diff / Document Comparer',
    shortName: 'Text Diff',
    description: 'Compare two text documents to find differences and changes.',
    longDescription: 'A robust client-side diff tool for comparing code, documents, and lists line by line.',
    category: 'text-tools',
    icon: 'git-commit',
    keywords: ['diff', 'compare', 'text diff', 'changes'],
    status: 'stable',
    featured: true,
    publishedAt: '2026-06-16',
  },
  {
    id: 'jwt-decoder',
    slug: 'jwt',
    name: 'JWT Decoder',
    shortName: 'JWT Decode',
    description: 'Decode and inspect JSON Web Tokens without sending data to a server.',
    longDescription: 'Securely decode JWTs in your browser to view the header, payload claims, and check expiry.',
    category: 'dev-tools',
    icon: 'lock',
    keywords: ['jwt', 'decode', 'token', 'inspect'],
    status: 'stable',
    featured: true,
    publishedAt: '2026-06-16',
  },
  {
    id: 'mock-data-generator',
    slug: 'mockdata',
    name: 'Mock Data / JSON Generator',
    shortName: 'Mock Data',
    description: 'Generate realistic mock data arrays in JSON, CSV, or SQL formats.',
    longDescription: 'Build a schema and instantly generate up to 1000 rows of fake data for testing and prototyping.',
    category: 'generators',
    icon: 'database',
    keywords: ['mock', 'fake data', 'json', 'csv', 'generate'],
    status: 'stable',
    featured: true,
    publishedAt: '2026-06-16',
  },
  {
    id: 'list-cleaner',
    slug: 'listcleaner',
    name: 'List Deduplicator & Sorter',
    shortName: 'List Cleaner',
    description: 'Remove duplicates, sort, and clean up text lists.',
    longDescription: 'Quickly process text lists: remove duplicate lines, sort alphabetically, trim whitespace, and filter empty lines.',
    category: 'text-tools',
    icon: 'list',
    keywords: ['list', 'deduplicate', 'sort', 'clean', 'lines'],
    status: 'stable',
    featured: false,
    publishedAt: '2026-06-16',
  },
  {
    id: 'text-case',
    slug: 'textcase',
    name: 'Text Case Master',
    shortName: 'Text Case',
    description: 'Convert text between 15+ different programming and standard cases.',
    longDescription: 'Instantly convert text to camelCase, snake_case, PascalCase, kebab-case, Title Case, and many more.',
    category: 'text-tools',
    icon: 'type',
    keywords: ['case', 'camelCase', 'snake_case', 'text formatting'],
    status: 'stable',
    featured: false,
    publishedAt: '2026-06-16',
  },
  {
    id: 'string-manipulator',
    slug: 'stringmanipulator',
    name: 'String Manipulator',
    shortName: 'String Manipulator',
    description: 'Chain powerful string operations: join lines, prefix/suffix, find & replace, filter, wrap, and more.',
    longDescription: 'A pipeline-based string manipulation tool. Stack multiple operations in order — join lines with a custom separator, add prefixes and suffixes, find & replace with regex, trim, wrap, number, filter, reverse, and repeat lines — all without writing a single line of code.',
    category: 'text-tools',
    icon: 'terminal',
    keywords: ['string', 'text', 'manipulate', 'join', 'prefix', 'suffix', 'replace', 'filter', 'wrap', 'lines', 'pipeline'],
    status: 'stable',
    featured: false,
    publishedAt: '2026-06-14',
  },
  {
    id: 'srt-cleaner',
    slug: 'srtcleaner',
    name: 'Subtitle / SRT Cleaner',
    shortName: 'SRT Cleaner',
    description: 'Strip formatting and speaker labels from SRT subtitle files.',
    longDescription: 'Clean messy subtitle files by removing HTML tags, speaker labels, and empty cues, or extract pure text transcripts.',
    category: 'cleaners',
    icon: 'film',
    keywords: ['srt', 'subtitle', 'transcript', 'clean'],
    status: 'stable',
    featured: false,
    publishedAt: '2026-06-16',
  },
  {
    id: 'url-params',
    slug: 'urlparams',
    name: 'URL Parameter Extractor',
    shortName: 'URL Params',
    description: 'Extract, decode, and remove tracking parameters from URLs.',
    longDescription: 'Parse long URLs to view all parameters in a clear table, and instantly strip common tracking tags like utm_source.',
    category: 'dev-tools',
    icon: 'link',
    keywords: ['url', 'parameters', 'tracking', 'utm', 'clean'],
    status: 'stable',
    featured: false,
    publishedAt: '2026-06-16',
  },
  {
    id: 'sql-formatter',
    slug: 'sqlformat',
    name: 'SQL Query Formatter',
    shortName: 'SQL Formatter',
    description: 'Prettify and format messy SQL queries.',
    longDescription: 'Format raw, single-line SQL queries into beautifully indented, readable statements.',
    category: 'formatters',
    icon: 'database',
    keywords: ['sql', 'format', 'beautify', 'query'],
    status: 'stable',
    featured: false,
    publishedAt: '2026-06-16',
  },
  {
    id: 'yaml-json',
    slug: 'yamljson',
    name: 'YAML to JSON Converter',
    shortName: 'YAML ↔ JSON',
    description: 'Convert between YAML and JSON formats locally.',
    longDescription: 'A fast, client-side converter to transform YAML configurations into JSON and vice versa.',
    category: 'converters',
    icon: 'file-text',
    keywords: ['yaml', 'json', 'convert', 'format'],
    status: 'stable',
    featured: false,
    publishedAt: '2026-06-16',
  },
  {
    id: 'cron-explainer',
    slug: 'cron',
    name: 'Cron Job Explainer',
    shortName: 'Cron Explainer',
    description: 'Translate cron expressions into human-readable text.',
    longDescription: 'Understand complex 5-field cron expressions in plain English and see the next upcoming run dates.',
    category: 'dev-tools',
    icon: 'clock',
    keywords: ['cron', 'schedule', 'expression', 'time'],
    status: 'stable',
    featured: false,
    publishedAt: '2026-06-16',
  },
  {
    id: 'html-escaper',
    slug: 'htmlescape',
    name: 'HTML Entity Escaper',
    shortName: 'HTML Escape',
    description: 'Encode and decode HTML entities safely.',
    longDescription: 'Convert special characters to their corresponding HTML entities, or decode entities back to plain text.',
    category: 'encoders',
    icon: 'code',
    keywords: ['html', 'entities', 'escape', 'encode', 'decode'],
    status: 'stable',
    featured: false,
    publishedAt: '2026-06-16',
  },
  {
    id: 'code-minifier',
    slug: 'minifier',
    name: 'CSS/JS Code Minifier',
    shortName: 'Code Minifier',
    description: 'Strip comments and whitespace from CSS and JavaScript.',
    longDescription: 'A lightweight minifier to clean up code snippets before pasting into production environments.',
    category: 'formatters',
    icon: 'file-text',
    keywords: ['minify', 'css', 'js', 'javascript', 'compress'],
    status: 'stable',
    featured: false,
    publishedAt: '2026-06-16',
  }
];

