import type { ToolDefinition } from '../types/tool';

export const tools: ToolDefinition[] = [
  // 1. The Developer Utility Suite
  {
    id: 'json-to-csv',
    slug: 'jsontocsv',
    name: 'JSON to CSV Converter',
    shortName: 'JSON → CSV',
    description: 'Convert JSON data to CSV format instantly with automatic schema detection.',
    longDescription: 'A robust client-side JSON to CSV converter that handles nested objects and arrays.',
    category: 'converters',
    icon: 'file-json',
    keywords: ['json', 'csv', 'converter', 'export'],
    status: 'stable',
    featured: true,
    publishedAt: '2026-06-15',
  },
  {
    id: 'json-formatter',
    slug: 'jsonformatter',
    name: 'JSON Formatter & Validator',
    shortName: 'JSON Format',
    description: 'Prettify and validate messy JSON API responses.',
    longDescription: 'Format, validate, and parse JSON data with clear error reporting and syntax highlighting.',
    category: 'formatters',
    icon: 'code',
    keywords: ['json', 'format', 'validate', 'pretty print'],
    status: 'coming-soon',
    featured: true,
    publishedAt: '2026-06-15',
  },
  {
    id: 'base64-encoder',
    slug: 'base64',
    name: 'Base64 Encoder/Decoder',
    shortName: 'Base64',
    description: 'Encode and decode Base64 strings and files.',
    longDescription: 'Quickly encode to Base64 or decode Base64 strings. Useful for API headers and images.',
    category: 'encoders',
    icon: 'hash',
    keywords: ['base64', 'encode', 'decode'],
    status: 'coming-soon',
    featured: true,
    publishedAt: '2026-06-15',
  },
  {
    id: 'timestamp-converter',
    slug: 'timestamp',
    name: 'Timestamp/Epoch Converter',
    shortName: 'Timestamp',
    description: 'Convert Unix timestamps to human-readable dates.',
    longDescription: 'Essential tool for logs and databases. Converts Unix epoch times to local/UTC dates and vice versa.',
    category: 'dev-tools',
    icon: 'clock',
    keywords: ['epoch', 'timestamp', 'date', 'unix', 'time'],
    status: 'coming-soon',
    featured: false,
    publishedAt: '2026-06-15',
  },
  {
    id: 'regex-tester',
    slug: 'regex',
    name: 'Regex Tester',
    shortName: 'Regex Test',
    description: 'Test your strings against regular expression patterns.',
    longDescription: 'Interactive regex tester with live highlighting and match group extraction.',
    category: 'dev-tools',
    icon: 'search',
    keywords: ['regex', 'regular expression', 'test', 'match'],
    status: 'coming-soon',
    featured: true,
    publishedAt: '2026-06-15',
  },
  
  // 2. The Content & Data Cleaners
  {
    id: 'html-to-markdown',
    slug: 'htmltomarkdown',
    name: 'HTML to Markdown Converter',
    shortName: 'HTML → MD',
    description: 'Convert HTML code into clean markdown.',
    longDescription: 'Easily turn blog post code into markdown for newsletters or Notion without losing formatting.',
    category: 'converters',
    icon: 'file-text',
    keywords: ['html', 'markdown', 'md', 'convert'],
    status: 'coming-soon',
    featured: false,
    publishedAt: '2026-06-15',
  },
  {
    id: 'word-counter',
    slug: 'wordcounter',
    name: 'Word & Character Counter',
    shortName: 'Word Count',
    description: 'Count words, characters, reading time, and readability score.',
    longDescription: 'Advanced text analysis showing reading time, Flesch-Kincaid readability, and keyword density.',
    category: 'text-tools',
    icon: 'type',
    keywords: ['word count', 'character count', 'reading time', 'readability'],
    status: 'coming-soon',
    featured: false,
    publishedAt: '2026-06-15',
  },
  {
    id: 'url-encoder',
    slug: 'urlencode',
    name: 'URL Encoder/Decoder',
    shortName: 'URL Encode',
    description: 'Encode or decode URL strings safely.',
    longDescription: 'Fix broken tracking links by properly encoding or decoding URL parameters.',
    category: 'encoders',
    icon: 'link',
    keywords: ['url', 'encode', 'decode', 'uri', 'escape'],
    status: 'coming-soon',
    featured: false,
    publishedAt: '2026-06-15',
  },

  // 3. The "Small Task" Generators
  {
    id: 'password-generator',
    slug: 'passwordgen',
    name: 'Secure Password Generator',
    shortName: 'Password Gen',
    description: 'Generate strong, secure passwords locally.',
    longDescription: 'Create highly secure passwords with toggles for symbols, numbers, and length. 100% client-side.',
    category: 'generators',
    icon: 'shield',
    keywords: ['password', 'generate', 'secure', 'random'],
    status: 'coming-soon',
    featured: true,
    publishedAt: '2026-06-15',
  },
  {
    id: 'uuid-generator',
    slug: 'uuid',
    name: 'UUID/GUID Generator',
    shortName: 'UUID Gen',
    description: 'Generate lists of v4 UUIDs instantly.',
    longDescription: 'Generate batches of 10-50 UUIDs with a single click. Ideal for database seeding.',
    category: 'generators',
    icon: 'database',
    keywords: ['uuid', 'guid', 'generate', 'v4', 'random'],
    status: 'coming-soon',
    featured: false,
    publishedAt: '2026-06-15',
  },
  {
    id: 'color-converter',
    slug: 'colorconverter',
    name: 'HEX to RGB/HSL Converter',
    shortName: 'Color Convert',
    description: 'Quickly convert between HEX, RGB, and HSL formats.',
    longDescription: 'A rapid color conversion tool for designers and developers.',
    category: 'dev-tools',
    icon: 'aperture',
    keywords: ['color', 'hex', 'rgb', 'hsl', 'convert'],
    status: 'coming-soon',
    featured: false,
    publishedAt: '2026-06-15',
  }
];
