export const walkthroughs = [
 {slug:'json-to-spreadsheet', title:'From nested JSON to spreadsheet columns', description:'Prepare a small API export, understand missing values, and avoid spreadsheet import surprises.', tool:'/jsontocsv/', sections:[
  {heading:'Start with two records', text:'An API often returns objects whose fields vary between records. Before converting a large export, copy two fictional records that represent the shapes you expect. Keep account IDs and other long identifiers as strings. The sample below deliberately includes a nested address, an array, a missing address, and an identifier with a leading zero.', code:'[{"id":"001","address":{"city":"Madrid"},"tags":["new","trial"]},{"id":"002","active":true}]'},
  {heading:'Choose the shape of the table', text:'Open JSON to CSV and paste the sample. Leave Include Headers and Flatten Objects checked, with a comma delimiter. The column set comes from all records, so active is included even though the first record has no active property. Arrays stay as JSON text inside one quoted cell. They are not expanded into separate rows.', code:'id,address.city,tags,active\n001,Madrid,"[""new"",""trial""]",\n002,,,true'},
  {heading:'Check what is lost', text:'A blank cell cannot distinguish a missing field from a JSON null. If that distinction matters, add a separate status field before converting. CSV also has no type metadata: 001 is a string in the source, but a spreadsheet can interpret it as the number 1. Import that column as text rather than opening the CSV with automatic type detection.'},
  {heading:'Resolve dotted keys explicitly', text:'A literal key named address.city would be ambiguous with the nested address object. Flattening rejects empty keys and keys containing dots rather than silently choosing one interpretation. Turn off Flatten Objects to keep the original top-level keys; nested objects will then be stored as JSON text in cells.'},
  {heading:'Import and validate', text:'Download the CSV and use your spreadsheet’s import dialog to choose the matching delimiter and UTF-8 text. Check the record count, headers, leading-zero identifiers, array cells, and a sample from the end of the file. Semicolon or tab may suit a particular import workflow, but both ends must use the same delimiter.'},
  {heading:'Before using a real export', text:'Do not assume quoted CSV is safe to open as formulas: spreadsheet programs can interpret text beginning with characters such as = as an expression. Import untrusted columns as text. For large files, use a streaming converter locally; this browser tool holds the source and result in memory. Use the JSON Formatter to locate a syntax problem before retrying conversion.'}
 ]},
 {slug:'clean-compare-lists',title:'Clean two lists before comparing them',description:'Separate formatting differences from meaningful additions and removals without losing identifiers.',tool:'/listcleaner/',sections:[
  {heading:'Define what counts as the same entry',text:'List cleaning can change meaning. For a case-sensitive identifier, Apple and apple may be different records. For a human-maintained shopping list, they may be the same entry. Decide this before enabling case-insensitive deduplication. Keep the untouched originals so you can revisit the choice.'},
  {heading:'Clean the first list',text:'Paste the following into List Cleaner. Enable trimming, removal of empty lines, and deduplication. Keep case-insensitive deduplication off and select alphabetical ascending order.',code:' apple \nbanana\napple\n\npear'},
  {heading:'Check the cleaned result',text:'Trimming makes the two apple entries equal; deduplication retains the first. Blank-line removal eliminates the separator. The expected result has three entries.',code:'apple\nbanana\npear'},
  {heading:'Apply identical settings to the second list',text:'Clean the second source with the same options. Comparing one cleaned list against an untouched list can produce misleading changes. Use the following already-clean list for the example.',code:'apple\npear\nplum'},
  {heading:'Compare as lines',text:'Open Text Diff. Put the first cleaned result in Original and the second in Modified. Choose line mode and select Compare. Expect two unchanged lines, one removed line (banana), and one added line (plum). The colour and direction tell you which source each change belongs to.'},
  {heading:'Understand the effect of sorting',text:'Sorting is appropriate when you care about membership. Do not sort a sequence where order matters, such as deployment steps or ranked results. Text Diff compares sequence order, so moved lines can appear as removal and addition. Word and character modes are useful for edits inside a sentence, but not for counting list entries.'},
  {heading:'Add formatting only after validation',text:'Use String Manipulator for prefixes, suffixes, or wrapping after you have checked membership changes. Adding quotation marks does not escape embedded quotes for JSON or SQL. For those destinations, use a real serializer or parameterised database interface. Large comparisons should be split into smaller excerpts if the tool reports its size limit.'}
 ]},
 {slug:'inspect-jwt',title:'Inspect JWT claims without mistaking them for verification',description:'Decode a fictional token, understand expiry, and distinguish readable claims from trusted authentication.',tool:'/jwt/',sections:[
  {heading:'Use a fictional token',text:'A JSON Web Token commonly contains three dot-separated segments: a header, payload, and signature. The first two encode JSON using Base64URL. This sample intentionally has no signature and an exp claim of zero. It is useful for inspecting the interface, not for authentication.',code:'eyJhbGciOiJub25lIn0.eyJzdWIiOiJkZW1vIiwiZXhwIjowfQ.'},
  {heading:'Read the decoded fields',text:'Paste the sample into JWT Decoder. You should see the following header and payload, with an Expired badge. The signature is not verified. The alg field is a claim inside the token; reading it is not an instruction to trust that algorithm.',code:'Header: {"alg":"none"}\nPayload: {"sub":"demo","exp":0}'},
  {heading:'Interpret expiry narrowly',text:'The exp claim is a NumericDate measured in seconds from the Unix epoch. A token is expired when the current time is at or after exp. Your browser clock controls this display. A Not expired badge means only that this numerical comparison passed. A missing exp claim produces no expiry assurance.'},
  {heading:'Know what decoding cannot prove',text:'Anyone can construct an encoded header and payload. Readability does not prove who issued them or whether the contents were altered. A real verifier must check the signature with a trusted key and an explicitly allowed algorithm, then enforce the application’s issuer, audience, time, and other claim requirements. This page does not perform those steps.'},
  {heading:'Debug with minimal disclosure',text:'A production token may grant access or expose personal information even when its payload is merely encoded. Prefer a fictional token or a carefully redacted example when reporting a bug. Tool code processes inputs locally, but that does not protect against browser extensions, clipboard history, screen sharing, or a compromised device.'},
  {heading:'Troubleshoot format errors',text:'The decoder requires three segments, valid Base64URL JSON objects for the header and payload, and a finite numeric exp if present. An encrypted JWE has a different structure and is outside this tool’s scope. For protocol definitions, see RFC 7519; use your authentication framework’s verifier when making an access-control decision.',link:'https://www.rfc-editor.org/rfc/rfc7519'}
 ]}
];
